### ISSUE TITLE
ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

### ISSUE THREAD

**Issue by C24IO** [kenstler/aws-ml-iot-lab#2]
https://github.com/kenstler/aws-ml-iot-lab/blob/58e1ee5849ea6502601f4b70f94e5b218a520c21/Prep_Challenge/SSD_Face_Detection_SageMaker_Endpoint.ipynb#L462

10.32.0.2 - - [12/Jun/2018:04:53:30 +0000] "GET /ping HTTP/1.1" 200 0 "-" "AHC/2.0"
10.32.0.2 - - [12/Jun/2018:04:53:35 +0000] "GET /ping HTTP/1.1" 200 0 "-" "AHC/2.0"
10.32.0.2 - - [12/Jun/2018:04:53:40 +0000] "GET /ping HTTP/1.1" 200 0 "-" "AHC/2.0"
10.32.0.2 - - [12/Jun/2018:04:53:45 +0000] "GET /ping HTTP/1.1" 200 0 "-" "AHC/2.0"
2018-06-12 04:53:45,681 INFO - botocore.vendored.requests.packages.urllib3.connectionpool - Starting new HTTPS connection (1): kenstler-aws-ml-iot-lab-trial.s3.amazonaws.com
[2018-06-12 04:53:45,755] ERROR in serving: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/container_support/serving.py", line 180, in _invoke
self.transformer.transform(content, input_content_type, requested_output_content_type)
File "/usr/local/lib/python2.7/dist-packages/mxnet_container/serve/transformer.py", line 62, in transform
return self.transform_fn(self.model, input_data, content_type, accept)
File "/opt/ml/code/mxnet_ssd_face_detection_rekognition.py", line 64, in transform_fn
push_to_s3(crop_img, i)
File "/opt/ml/code/mxnet_ssd_face_detection_rekognition.py", line 33, in push_to_s3
Key=key)
File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 612, in _make_api_call
raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
[2018-06-12 04:53:45,756] ERROR in serving: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
10.32.0.2 - - [12/Jun/2018:04:53:45 +0000] "POST /invocations HTTP/1.1" 500 0 "-" "AHC/2.0"

**Comment by C24IO** [comment]
Was resolved when AmazonS3FullAccess was attached. Seems the custom policy of "Anybucket" is not sufficient?

**Comment by kenstler** [comment]
Thanks, will include in the instructions.
